### ISSUE TITLE
Musik

### ISSUE THREAD

**Issue by wld-16** [timheesch/Projekt-A-#7]
- Background track:
  1. Option 3 versiedene Tracks
  2. Option 1 Track, der pro ebene eine Oktave höher geht
- Sounds:
  Verschieben, Rausschlagen

**Comment by cpt-fuzzy** [comment]
Ich hätte hier eine erste Ladung an Backgroundtrack Ideen, angelehnt an die Settings-Idee: Erde, Himmel, All. Paar Fehler/Verspieler sind drin und die All-Version ist ein wenig übersteuert :D Meinungen?

https://www.dropbox.com/sh/5eqg8994q9ztfcq/AAByJVOLmSNRSsh_doTUeJsLa?dl=0

**Comment by florianvoelkers** [comment]
Also ich finde Sky und Space passen perfekt. Der Erd-Song ist schon etwas sehr langsam und ich weiß nicht, ob er so reinpasst. Für mich ist der vielleicht ein bisschen zu nett, eine gewisse Antizipation der Feindlichkeit sollte schon da sein. Das ist aber Gemecker auf hohem Niveau. Der Grund-Sound ist auch ziemlich geil an sich. Da würde ich nicht viel ändern.

**Comment by cpt-fuzzy** [comment]
Ich hab nochmal einen ganz anderen Ansatz in den Ordner gepackt, müsste über den gleichen Link zu finden sein. Ist etwas düsterer, mysteriöser, bin aber auch nicht sicher, ob dass überhaupt passt. Musikalische Ausgüsse um 10uhr abends halt.
